name: pokey
description: An app displaying list of pokemons using the pokemon API.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # A package used to easily access state from anywhere in the app while being 
  # robust and easily testable
  hooks_riverpod: ^2.0.2

  # A package thayt helps with network calls
  http: ^0.13.5

  # A package that helps to view SVG images in Flutter
  flutter_svg: ^1.1.5

  # A package to include fonts from fonts.google.com in your Flutter app.
  google_fonts: ^2.2.0

  # A package to make the loading state give a betters user experience 
  shimmer: ^2.0.0

  #These two packages helps to store values to the local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #this package helps to load a network image, then caches it for future calls
  cached_network_image: ^3.2.1
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # A Dart mock library which simplifies mocking with null safety support 
  # and no manual mocks or code generation
  mocktail: ^0.2.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  # A package that helps to generate values from hive_generator (for this app)s
  build_runner: ^2.3.0

  # This helps to geerate Hive Models for storage purposes
  hive_generator: ^1.1.3

  #This is a package that helps to easily configure the app's launcher icon
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pokedex_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro

